### ISSUE TITLE
Can we get a 2023.02.00-alpha02?

### ISSUE THREAD

**Issue by benwicks** [chrisbanes/compose-bom#13]
It seems there has been another wave of alpha library releases: https://androidx.tech/blog/2023/01/25/late-january-artifact-wave.html

**Comment by chrisbanes** [comment]
Yep, I've been trying all day but Maven Central has been having a lot of issues.

I just pushed up a version bump commit, so hopefully it works this time (I've seen reports that things are better).

**Comment by chrisbanes** [comment]
Still failing unfortunately https://github.com/chrisbanes/compose-bom/actions/runs/4019793013/jobs/6907035699

**Comment by chrisbanes** [comment]
[v2023.02.00-alpha02](https://github.com/chrisbanes/compose-bom/releases/tag/v2023.02.00-alpha02) has been released!
