### ISSUE TITLE
How can I use Compose 1.4.1

### ISSUE THREAD

**Issue by mac229** [chrisbanes/compose-bom#38]
Hi,
Compose Bom targets to compose 1.4.0:
https://github.com/chrisbanes/compose-bom/commit/58353e732d95fd2b10da0ca7276bac58629c683d

However there is the stable compose version 1.4.1.
How can I use it with Bom?

**Comment by chrisbanes** [comment]
This targets the version latest version. For 1.4.1 you'll have to wait for the next official BOM
