### ISSUE TITLE
Release for Compose 1.5.0-beta03?

### ISSUE THREAD

**Issue by joharei** [chrisbanes/compose-bom#62]
Looks like this beta wave didn't get a release:

https://developer.android.com/jetpack/androidx/versions/all-channel#june_28_2023

**Comment by chrisbanes** [comment]
It's because we're already on 1.6.0-alpha01 from https://github.com/chrisbanes/compose-bom/commit/36403d47a5d8ddc347b772c5aa3b6d4f756a5947. Create different release trains is out of scope here unfortunately.
